AddressLine1: 450 Church St
AddressLine2: Physics Dept, University of Michigan
City: Ann Arbor
Country: United States
Description: University of Michigan/Michigan State University combined site for USATLAS
  computing.
ID: 10054
Latitude: 42.291637
LongName: Atlas Great Lakes Tier2
Longitude: -83.71831
State: MI
Zipcode: 48109-1040
