AddressLine1: Av. Prof. Luciano Gualberto, 71, travessa 3
City: São Paulo
Country: Brazil
ID: 10136
Latitude: -23.557103
LongName: "Universidade de S\xE3o Paulo - Laborat\xF3rio de Computa\xE7\xE3o Cient\xED\
  fica Avan\xE7ada"
Longitude: -46.731999
State: SP
Zipcode: 05508-010
