City: Kitchener
Country: Canada
Description: A virtualized CE and WN cluster to take advantage of otherwise unused
  resources at CancerComputer's cluster in Kitchener
ID: 10234
Latitude: 43.4235682
LongName: CancerComputer-Kitchener-Ardelt
Longitude: -80.4759616
State: 'ON'
Zipcode: N2C2M3
