AddressLine1: Avenida Francisco J. Mujica S/N
City: MORELIA
Country: MEXICO
Description: University of Morelia Michoacan
ID: 10180
Latitude: 19.687771
Longitude: -101.209067
State: MICHOACAN
Zipcode: '58030'
