AddressLine1: 2020 Ridge Ave
City: Evanston
Country: USA
Description: Tier3 Facility for Northwestern University's High Energy Physics Group,
  analyzing data from the CMS collaboration at CERN.
ID: 10183
Latitude: 42.05408
LongName: Northwestern University Tier3 CMS
Longitude: -87.68809
State: IL
Zipcode: '60201'
