AddressLine1: Na Slovance 1999/2
City: Prague 8
Country: Czech Republic
Description: Regional Computing Center for Particle Physics (RCCPP) is the biggest
  site in the Czech Republic for simulations and data processing for particle physics
  experiments. It is located in the Institute of Physics of the Academy of Sciences
  of the Czech Republic.
ID: 10189
Latitude: 50.123424
Longitude: 14.468787
Zipcode: 182 21
