AddressLine1: 2020 Ridge Ave.
City: Evanston
Country: USA
Description: Northwestern University Medium Energy Physics Group
ID: 10190
Latitude: 42.05408
LongName: NU MEP OSG
Longitude: -87.68809
State: IL
Zipcode: '60201'
