City: Upton
Country: USA
Description: A relatively small pool (initially 29 hosts).  It is only accessible
  from the BNL site, and is only for STAR jobs.
ID: 10205
Latitude: 40.879129
Longitude: -72.8767
State: NY
Zipcode: '11973'
