City: Nashville
Country: USA
Description: Test site for integrating EC2 into CMS' infrastructure
ID: 10147
Latitude: 36.143827
LongName: Vanderbilt Cloud Interface
Longitude: -86.796455
State: TN
Zipcode: '37240'
