City: Syracuse
Country: United States
Description: Syracuse University Information Technology Services Research Clusters
ID: 10194
Latitude: 43.0385961
LongName: Syracuse University Information Techology Services
Longitude: -76.13268340000002
State: NY
Zipcode: '13244'
