AddressLine1: 5735 S Ellis ave
City: Chicago
Country: USA
Description: University of Chicago Campus Grid and ITB resources
ID: 10181
Latitude: 41.791219
Longitude: -87.601384
State: IL
Zipcode: '60637'
