AddressLine1: Physics Building
AddressLine2: Science Drive
City: Durham
Country: United States
Description: Duke University HEP group Tier 3 site
ID: 10091
Latitude: 36.003111
LongName: Duke University HEP Tier 3
Longitude: -78.942304
State: North Carolina
Zipcode: '27708'
