AddressLine1: 1110 W Green St
City: Urbana
Country: United States
Description: The High Energy Physics at the University of Illinois is a member of
  ATLAS
ID: 10077
Latitude: 40.109647
LongName: University of Illinois High Energy Physics
Longitude: -88.21246
State: IL
Zipcode: '61801'
