AddressLine1: CERN
AddressLine2: CH-1211 Geneva 23
City: Geneva
Country: Switzerland
Description: Cluster intended for use by Neutrino Platform experiments at CERN.
ID: 10216
Latitude: 46.22932
LongName: CENF Neutrino Platform
Longitude: 6.054174
Zipcode: CH-1211
