AddressLine1: Parque Industrial Carlos Velez Pombo
AddressLine2: Ternera Km 1 via Turbaco
City: Cartagena
Country: Colombia
Description: Site Asociated to a GCVO and GCEDU
ID: 10152
Latitude: 10.370536
LongName: Unitecnologica
Longitude: -75.465742
State: Bolivar
Zipcode: '130010'
