AddressLine1: 150 W. University Blvd
AddressLine2: PSS
City: Melbourne
Country: United States
Description: HEP computing and US CMS at CERN
ID: 10067
Latitude: 28.077494
LongName: Florida Tech Physics and Space Sciences
Longitude: -80.61987
State: FL
Zipcode: '32901'
