City: Dallas
Country: United States
Description: The University of Texas at Dallas Atlas Tier3gs (aka "mini-Tier2") GRID
  production site
ID: 10090
Latitude: 32.734332
Longitude: -96.709986
State: Texas
Zipcode: '75080'
