AddressLine1: 114 Nichols Hall
AddressLine2: Kansas State University
City: Manhattan
Country: US
Description: The Beocat compute cluster at Kansas State University
ID: 10120
Latitude: 39.186514
Longitude: -96.58088
State: KS
Zipcode: '66506'
