City: Urbana
Country: US
Description: Administrative group for CIGI resources
ID: 10106
Latitude: 40.107487
LongName: CyberInfrastructure and Geospatial Information Laboratory
Longitude: -88.22603
State: Illinois
Zipcode: '61801'
