AddressLine1: California State University, Fresno, Department of Physics
City: Fresno
Country: USA
Description: California State University, Fresno, ATLAS T3g site
ID: 10159
Latitude: 36.812927
LongName: CSU Fresno T3
Longitude: -119.746857
State: CA
Zipcode: 93740-8027
