AddressLine1: 1111 South University Parks Drive
City: Waco
Country: USA
Description: Baylor University T3 CMS Cluster
ID: 10112
Latitude: 31.551111
LongName: Baylor University T3
Longitude: -97.118368
State: TX
Zipcode: '76706'
