AddressLine1: Building 360
AddressLine2: ANL
City: Lemont
Country: USA
Description: Argonne National Lab Analysis Support Center
ID: 10122
Latitude: 41.705917
LongName: Argonne National Lab Analysis Support Center
Longitude: -87.975157
State: Illinois
Zipcode: '60439'
