AddressLine1: 11200 SW 8th St
AddressLine2: PC417
City: Miami
Country: United States
Description: FIU Panther cluster sponsored by campus central IT division.
ID: 10204
Latitude: 25.758
LongName: FIU HPC Division of Information Technology
Longitude: -80.376
State: Florida
Zipcode: '33174'
