City: East Lansing
Country: United States
Description: D0 and Atlas Tier3 of the High Energy Physics Group at Michigan State
  University
ID: 10018
Latitude: 42.603642
LongName: MSU OSG
Longitude: -84.79248
State: MI
Zipcode: '48824'
