AddressLine1: Department of Physics CP202
AddressLine2: 11200 SW 8th Street
City: Miami
Country: USA
Description: CMS Tier3 site located at Florida International Univerisity
ID: 10146
Latitude: 25.758609
LongName: FIU CMS Tier3 meta cluster
Longitude: -80.372361
State: Florida
Zipcode: '33199'
