City: University
Country: United States
Description: This is the University of Mississippi's High Energy Physics computing
  facility.
ID: 10081
Latitude: 34.366302
Longitude: -89.53721
State: MS
Zipcode: '38677'
