City: Washington DC
Country: USA
Description: PerfSONAR instance at Washington Information Exchange
ID: 10195
Latitude: 37.401394
LongName: Washington Information Exchange
Longitude: -116.867846
Zipcode: '20004'
