AddressLine1: University of California Irvine
City: Irvine
Country: U.S.A
Description: ATLAS UC Irvine Tier-3
ID: 10126
Latitude: 33.643474
LongName: ATLAS UC Irvine Tier-3
Longitude: -117.840128
State: CA
Zipcode: 92697-4575
