City: Beijing
Country: China
Description: The Computer Network Information Center(CNIC) is a subsidiary research
  institute of the Chinese Academy of Sciences (CAS). CNIC is a support institution
  for sustainable construction, operation and service for informatization of Chinese
  Academy of Sciences, an operation management institution for basic resources of
  China's Internet, R&D base for advanced network and high-end application technology,
  and important component of the advanced S&T networks both at home and abroad. CNIC
  boasts seven service/research centers, including China Science and Technology Network
  Center (CSTNet), Scientific Data Center, Supercomputing Center, ARP (Academia Resource
  Planning) Operation Support Center, China Internet Network Information Center (CNNIC),
  Collaborative Environment Research Center (CERC) and Online Popular Science Education
  Center.
ID: 10101
Latitude: 39.987511
LongName: Chinese Academy of Sciences (CAS) Computer Network Information Center
Longitude: 116.308823
State: Haidian District
Zipcode: '100190'
