AddressLine1: University of Connecticut Health Center
AddressLine2: 263 Farmington Avenue
City: Farmington
Country: United States
Description: A 29 node, 57 CPU Compute Element
ID: 10093
Latitude: 41.729962
LongName: University of Connecticut Health Center_CompBioGrid
Longitude: -72.791183
State: Connecticut
Zipcode: '06030'
