City: Baton Rouge
Country: United States
Description: LONI resources located at Louisiana State University
ID: 10014
Latitude: 30.413299
LongName: Louisiana Optical Network Initiative
Longitude: -91.17918
State: LA
Zipcode: '70803'
