AddressLine1: 514 University Ave
City: Selinsgrove
Country: USA
Description: Susquehanna University Physics Dept.
ID: 10142
Latitude: 40.798506
LongName: Susquehanna University Physics Dept.
Longitude: -76.873155
State: PA
Zipcode: '17870'
