City: New York
Country: USA
Description: Tier3g cluster devoted to the analysis of the data collected by the ATLAS
  detector.
ID: 10144
Latitude: 40.729942
LongName: NYU ATLAS Tier3
Longitude: -73.994486
State: NY
Zipcode: '10003'
