AddressLine1: via Marzolo 8
City: Padova
Country: Italy
Description: Grid site supporting SBGrid VO for interoperability tests between WeNMR/EGI
  and SBGrid/OSG. It hosts a glideinWMS submit node connected to the HMS SBGrid VO
  Frontend.
ID: 10167
Latitude: 45.409357
Longitude: 11.885952
Zipcode: '35131'
