AddressLine1: 1668 S Martin Luther King
City: Tallahassee
Country: USA
ID: 10138
Latitude: 30.428152
LongName: AstroParticle and Cosmic Radiation Detector Research and Development Laboratory
Longitude: -84.284816
State: Florida
Zipcode: '32307'
