AddressLine1: 10 W. 35th Street, 8th Floor, 8E3-2
City: Chicago
Country: USA
Description: Illinois Institute of technology  HPC & HTC computing resources at Research
  Data Center
ID: 10212
Latitude: 41.8349
LongName: Illinois Institute of Technology
Longitude: -87.627
State: IL
Zipcode: '60616'
