AddressLine2: 710 N Lakeshore Drive
City: Chicago
Country: US
Description: The Starlight PoP in Chicago run by Northwestern/MREN
ID: 10197
Latitude: 37.401394
LongName: StarLight
Longitude: -116.867846
State: IL
Zipcode: '60611'
