AddressLine1: Av. IPN 2508
AddressLine2: Col. San Pedro Zacatenco
City: Mexico
Country: Mexico
Description: |-
  The Center for Research and Avanced Studies of I.P.N. (CINVESTAV) is a public organization dedicated to promote, develop, and teach research in science. The Institution counts 37 Departments, separated into 4 research areas; Exact Sciences, Biology & Medicine, Technology &
  Engineering, and Social Sciences & Humanities. CINVESTAV have 9 Centers across Mexico which offer a variety of Academic programs and research areas.
ID: 10012
Latitude: 19.50798
LongName: Centro de Investigacion y de Estudios Avanzados del IPN
Longitude: -99.129424
State: Distrito Federal
Zipcode: '07360'
